# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_album_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='encrypted_id',
            field=models.CharField(default='', max_length=250),
        ),
    ]
