# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_song_encrypted_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
    ]
